# Site settings
title: Minimal Staticman v3 Demo
subtitle: A barebone GitHub Pages with static comments
email: your-email@domain.com
description: Test
baseurl: ""
url: "https://wini3d.github.io/mini//"
locale: en
github_username:  wini3d

# Build settings
markdown: kramdown

staticman:
  api: "https://staticman3.herokuapp.com/v3/entry/github/vincenttam/TestStaticmanLab/master/comments"
  path: "_data/comments/test-slug"
